### PR TITLE
Feature/landing-page

### PR DESCRIPTION
**Pull request by MarwanBz**
Hey,
I made this PR so check it out and let me know if everything is okay

### CODE REVIEW

**Review by parykhan-jameel — APPROVED** [review]
all good, great work

**Comment by M-AminAlizadeh** [comment]
@MarwanBz Thank you 
I will review it ASAP.

**Review by mohammadamin-alizadeh — CHANGES_REQUESTED** [review]
Hey @MarwanBz 

💥 Thank you for your effort The landing page is awesome now 💥

🎯 Try to fix these issues before merging:

1. kindly use an empty person image instead of this (use this [link](https://pixabay.com/vectors/blank-profile-picture-mystery-man-973460/) ):
image

2. The header internal links especially **Team** don't work when the user clicks on it
image

When users click on the team link it should show the teams section to the user (other links don't matter at this level but the team should work) for more info about the internal link check out [this page](https://stackoverflow.com/questions/65784386/html-how-to-use-internal-links-to-text-in-a-page)

Thank you again for your great job

**Comment by MarwanBz** [comment]
thanks, guys for the amazing feedback!

@M-AminAlizadeh 
@parykhan-jameel 

could you please check the new changes and let me know

**Review by mohammadamin-alizadeh — APPROVED** [review]
There is nothing to say just it's time to merge it

**Pull request merged**
